### ISSUE TITLE
How to add a gallery to a page.

### ISSUE THREAD

**Issue by siriusweb** [pyrocms/galleries#30]
Greetings,

I am new to PyroCMS and would like to know how to add a gallery to a page.  I have successfully created a gallery and uploaded the photos, however what is the syntax or code needed to add the gallery to a page.  These instructions were not available in the ReadMe file.

Regards,
K. L. Graham

**Comment by RyanThompson** [comment]
Hey there! This module has its own routes rather than a plugin: https://github.com/pyrocms/galleries/blob/2.2/master/config/routes.php

**Comment by siriusweb** [comment]
Thank you for your prompt response.  So pretty much a shortcode (ex. {{ mygallery-photos }} ) cannot be used to embed the gallery into a page?  I just double checked the routes.php file that I downloaded and it looks very different.  This must have been a recent addition.  However, I'm still unclear on how to make it display on a page.  I will download the version of the files from Github to see if that makes a difference.

**Comment by RyanThompson** [comment]
This is for a 2.2 version of pyrocms right? Actually it does look like there is a plugin, my mistake: https://github.com/pyrocms/galleries/blob/2.2/master/plugin.php

**Comment by siriusweb** [comment]
Yes, I'm using version 2.2.1.  I'm about the install the version from the link you sent.  What I had was a different version. https://github.com/ChristianGiupponi/PyroCMS-Galleries

**Comment by siriusweb** [comment]
I just installed galleries-2.2-master and it appears that it is not compatible with PyroCMS version 2.2.1.  There were 3 PHP errors.  Is there another option (i.e. 3rd party gallery) that works well with PyroCMS?
